<?php
declare(strict_types=1);
require_once __DIR__ . '/../app/lib/security.php';
require_admin();

$pdo=db();$errors=[];$edit=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf($_POST['csrf_token']??null);$action=$_POST['action']??'';
    try{
        if($action==='save'){
            $username=trim((string)($_POST['username']??''));$nome=trim((string)($_POST['nome']??''));$status=$_POST['status']??'A';$tipo=$_POST['tipo']??'U';$senha=(string)($_POST['senha']??'');$isEdit=isset($_POST['editing'])&&$_POST['editing']==='1';
            if(!preg_match('/^[A-Za-z0-9_.-]{3,50}$/',$username))$errors[]='Username deve ter 3-50 caracteres e conter apenas letras, números, ponto, hífen ou sublinhado.';if($nome==='')$errors[]='Nome é obrigatório.';if(!in_array($status,['A','I','B'],true))$errors[]='Status inválido.';if(!in_array($tipo,['A','U'],true))$errors[]='Tipo inválido.';if(!$isEdit&&strlen($senha)<8)$errors[]='Senha inicial deve possuir pelo menos 8 caracteres.';
            if(!$errors){if($isEdit){$s=$pdo->prepare($senha!==''?'UPDATE usuarios SET nome=?,status=?,tipo=?,senha=?,primeiro_acesso=1 WHERE username=?':'UPDATE usuarios SET nome=?,status=?,tipo=? WHERE username=?');if($senha!=='')$s->execute([$nome,$status,$tipo,password_hash($senha,PASSWORD_DEFAULT),$username]);else$s->execute([$nome,$status,$tipo,$username]);audit("Usuário {$username} atualizado.");flash('success','Usuário atualizado.');}else{$s=$pdo->prepare('INSERT INTO usuarios(username,senha,nome,status,tipo,dt_acesso,tentativas_falhas,bloqueado_ate,primeiro_acesso) VALUES(?,?,?,?,?,NULL,0,NULL,1)');$s->execute([$username,password_hash($senha,PASSWORD_DEFAULT),$nome,$status,$tipo]);audit("Usuário {$username} cadastrado.");flash('success','Usuário cadastrado.');}redirect('usuarios.php');}
        }elseif($action==='delete'){$username=trim((string)$_POST['username']);if($username===current_user()['username']){$errors[]='O administrador não pode excluir a própria conta.';}else{$s=$pdo->prepare('DELETE FROM usuarios WHERE username=?');$s->execute([$username]);audit("Tentativa de exclusão do usuário {$username}.");flash('success','Usuário excluído se não possuir logs vinculados.');redirect('usuarios.php');}}
    }catch(PDOException $e){if((int)($e->errorInfo[1]??0)===1062)$errors[]='Username já cadastrado.';elseif((int)($e->errorInfo[1]??0)===1451)$errors[]='Usuário possui logs de auditoria e não pode ser excluído. Inative a conta.';else$errors[]='Não foi possível concluir a operação.';}
}
if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT username,nome,status,tipo FROM usuarios WHERE username=?');$s->execute([$_GET['edit']]);$edit=$s->fetch()?:null;}
$list=$pdo->query('SELECT username,nome,status,tipo,dt_acesso,bloqueado_ate FROM usuarios ORDER BY nome')->fetchAll();
$title='Usuários';require __DIR__.'/../app/views/header.php';
?>
<div class="page-head"><div><h1>Usuários</h1><p class="muted">Área administrativa: contas, status, perfil e senha.</p></div></div>
<?php if($errors):?><div class="errors"><ul><?php foreach($errors as $e):?><li><?=h($e)?></li><?php endforeach;?></ul></div><?php endif;?>
<div class="grid"><div class="card"><h2><?= $edit?'Editar usuário':'Novo usuário' ?></h2><form method="post" data-submit-once><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="save"><input type="hidden" name="editing" value="<?= $edit?'1':'0' ?>">
<div style="margin-bottom:12px"><label>Username</label><input name="username" maxlength="50" required <?= $edit?'readonly':'' ?> value="<?=h($edit['username']??'')?>"></div><div style="margin-bottom:12px"><label>Nome</label><input name="nome" maxlength="80" required value="<?=h($edit['nome']??'')?>"></div><div style="margin-bottom:12px"><label>Senha <?= $edit?'(opcional para alterar)':'' ?></label><input type="password" name="senha" minlength="8" autocomplete="new-password"></div>
<div class="form-grid"><div><label>Status</label><select name="status"><option value="A" <?=($edit['status']??'A')==='A'?'selected':''?>>Ativo</option><option value="I" <?=($edit['status']??'')==='I'?'selected':''?>>Inativo</option><option value="B" <?=($edit['status']??'')==='B'?'selected':''?>>Bloqueado</option></select></div><div><label>Tipo</label><select name="tipo"><option value="A" <?=($edit['tipo']??'U')==='A'?'selected':''?>>Administrador</option><option value="U" <?=($edit['tipo']??'U')==='U'?'selected':''?>>Usuário comum</option></select></div></div>
<div class="actions" style="margin-top:12px"><button type="submit">Salvar</button><?php if($edit):?><a class="btn btn-secondary" href="usuarios.php">Cancelar</a><?php endif;?></div></form></div>
<div class="card"><h2>Contas cadastradas</h2><div class="table-wrap"><table><thead><tr><th>Usuário</th><th>Nome</th><th>Status</th><th>Tipo</th><th>Último acesso</th><th>Ações</th></tr></thead><tbody><?php foreach($list as $u):?><tr><td><?=h($u['username'])?></td><td><?=h($u['nome'])?></td><td><span class="badge <?= $u['status']==='A'?'badge-success':'badge-danger' ?>"><?=h(['A'=>'Ativo','I'=>'Inativo','B'=>'Bloqueado'][$u['status']]??$u['status'])?></span></td><td><?= $u['tipo']==='A'?'Administrador':'Usuário comum' ?></td><td><?=h($u['dt_acesso']??'Nunca')?></td><td class="actions"><a class="btn btn-small" href="?edit=<?=urlencode($u['username'])?>">Editar</a><?php if($u['username']!==current_user()['username']):?><form method="post"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="username" value="<?=h($u['username'])?>"><button class="btn-danger btn-small" data-confirm="Excluir usuário? A exclusão falhará se houver logs vinculados.">Excluir</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<?php require __DIR__.'/../app/views/footer.php'; ?>
